ALTER TABLE "JobApplication"
ADD COLUMN IF NOT EXISTS "rating" INTEGER,
ADD COLUMN IF NOT EXISTS "ref1Company" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref1JobTitle" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref1Name" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref1Phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref2Company" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref2JobTitle" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref2Name" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "ref2Phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "rejectionNote" TEXT;

ALTER TABLE "JobApplication" ALTER COLUMN "ref1Company" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref1JobTitle" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref1Name" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref1Phone" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref2Company" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref2JobTitle" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref2Name" DROP DEFAULT;
ALTER TABLE "JobApplication" ALTER COLUMN "ref2Phone" DROP DEFAULT;
